### ISSUE TITLE
Review and approval

### ISSUE THREAD

**Issue by Kariton** [evrardjp/ansible-collection-ha#1] opened 2022-07-20 05:31 UTC
How can a review and approval process look like?

I understand that each review will take place within its PR.

What must a maintainer do before a PR will get a review - or be approved. 
- what standards do roles have to met?
  - directory structure
  - role naming (by "new" roles the "new" standard)
- is a galaxy release mandatory?
- what about molecule (or other) testing? (this seems fairly obvious)

**Comment by evrardjp** [comment] 2022-07-20 07:39
Keep in mind I am new to collections :)

Let's do one question at a time.

What standards do role have to met... regarding naming: My expectation is that the role can be triggered through an include_role, which means it should be a friendly name like evrardjp.ha.keepalived, evrardjp.ha.haproxy, etc. Does that help? 

What standards do role have to met... regarding directory structure: Any role that's bootstrapped with ansible-galaxy should be okay. What does this mean? At least a README on the usage of the role plus the defaults/ vars/ tasks/ meta/ folders.

Side topic, I would love to come with an agreement on the 'best practices' for the roles.
For example, the use of ansible_facts instead of the full hostvars (in case someone doesn't inject them), or the multi distro support by doing the right variables includes. We could also determine the base distros to support. To be determined together.

The role is expected to be tested (for regressions/changes in user input *1), but I don't care how (molecule, tox, your own playbooks), nor will I double check (it's a bonus, not a strong requirement, explanation on why below).

The role is expected to be _versioned_ or at least provide release information about changes (changelog). This is important, as this will allow us to determine the version to use in the collection. (If we bump the roles to their latest HEAD of the branch (or latest tag), we can know if there were major changes in each of the roles, which in turn deserve a major semver change in the collection)

Is a galaxy release mandatory for the role? Not at all. 

In terms of testing, I want to highlight that the goal of the collection is to ensure the integration of roles together. So this means that the collection need to be tested together. For this, we'll have github actions testing in this repository.
It will be in charge of ensuring that roles work well together. Not sure whether I will use molecule for that, it seems more hassle than it is worth. I will check what ansible-test does. If you have expertise, please share.

Finally, I think we need to add the topic of governance: Who takes decision, and can lead this.
I work on a meritocracy basis. I work with lazy consensus (https://www.apache.org/foundation/glossary.html#LazyConsensus) in general.
I don't care about the prestige idea of "maintainer" (for me it's far from prestigious).
So if you contribute, you can expect to be considered as maintainer from day1. I will make sure we have a codeowners file for this. As a contributor (so basically ... anyone), you can take decisions for the project. I generally won't object improvements, except if it really goes against the idea/concept of this work. We'll see when/if we eventually get there.

*1: This is very vague, and I assume ppl use their best judgement. The goal here is to ensure that when an example is provided in the collection, it actually does what it should be, because the role is respecting the input "contract". Not really sure how I can phrase this :)

**Closed as completed** 2024-09-19 16:51 UTC
